# 4. Geospatial processing

### [read] Summarise data availability of addresses among the fixed_table
- So we know what we're working with in terms of different types

In [1]:
# ### [read] Summarise data availability of addresses among the fixed_table
# - So we know what we're working with in terms of different types
# This should be lat/long, full address, address decomposed across the different fields, just postcode, the nothing
# And if its primary trading address or registered office address
import ibis

address_hierachy = [
    {'primary_trading_address_latitude', 'primary_trading_address_longitude'},
    {'primary_trading_address'},
    {'ro_latitude', 'ro_longitude'},
    {'ro_address'},
    {'ro_address_line_1', 'ro_full_postcode'},
    {'ro_full_postcode'},
    {'ro_postcode'}
]

# Dynamically builds an ibis.cases() expression from a list of column sets.
def build_location_source_cases(table: ibis.expr.types.Table, hierarchy: list[set]):
    cases_list = []
    
    for i, field_set in enumerate(hierarchy, start=1):
        # 1. Build the logical condition: EVERY column in the set must be not-null
        condition = None
        for col_name in field_set:
            is_not_null = table[col_name].notnull()
            condition = is_not_null if condition is None else condition & is_not_null
        
        # 2. Store as a (condition, result_value) tuple
        cases_list.append((condition, i))
        
    # 3. Unpack the list of tuples into ibis.cases. 
    # Fallback MUST be an integer to match the column type.
    fallback_lvl = len(hierarchy) + 1
    return ibis.cases(*cases_list, else_=fallback_lvl)

### [write] Add the ONS postcode directory to the database

In [ ]:
# Add input/NSPL_MAY_2026_UK.csv as a table to the database
# Keep only columns pcds, lat, and long
import ibis
import pandas as pd
from utils.f_0_dirs import get_data_dirs

table_name = "ref_ons_postcode"
file_name = "skinny_NSPL_MAY_2026_UK.csv"
keep_cols = { "pcds", "lat", "long" }

# Initialize connection
dirs = get_data_dirs(segment="descriptives")
con = ibis.duckdb.connect(str(dirs.db_path))

csv_file = f"{dirs.input_dir}/{file_name}"

df_raw = pd.read_csv(csv_file, usecols=list(keep_cols))
# df_raw.to_csv(f"{dirs.input_dir}/skinny_{file_name}")
if len(set(df_raw.columns).intersection(keep_cols)) != len(keep_cols):
    for col in keep_cols:
        if col not in set(df_raw.columns):            
            raise ValueError(f"Expected {col} in columns: missing")

codes_length = len(df_raw)
display(df_raw.sample(20))

❌ DATA_DIR path does not exist or is not a directory: /mnt/h/Other computers/My computer/fame_clean/1_FAME_raw_data/2025.07.30

In [3]:
con.create_table(table_name, df_raw, overwrite=table_name in con.list_tables())
table_ref = con.table(table_name)
rows_count = table_ref.count().execute()
print(f"{rows_count:,} rows in new table {table_name}")
print("Sample:")
display(table_ref.sample(20 / rows_count).execute())

2,726,477 rows in new table ref_ons_postcode
Sample:

        pcds        lat      long
0    BH5 1JP  50.722251 -1.835667
1   BT20 4WU  99.999999  0.000000
2    EX6 8PL  50.628684 -3.451323
3    HR4 9UU  52.071887 -2.721395
4   KT20 6NW  51.285990 -0.214215
5     L4 5SH  53.441079 -2.965222
6   LL13 7EY  53.036467 -2.991550
7    ME2 1BQ  51.352562  0.442107
8   NP23 5TP  51.798839 -3.225913
9   PL22 0AR  50.409628 -4.673098
10   RG1 3GB  51.456544 -0.960393
11  SA10 9EE  51.765848 -3.719049
12   SE5 5BF  51.473777 -0.096518
13  SK10 4QB  53.286750 -2.182448
14   SO1 5EZ  50.919830 -1.420829
15  TS10 3DT  54.617883 -1.061739
16  TW18 2YT  51.434063 -0.530096
17  TW18 3BU  51.435349 -0.532271
18   WA6 0JG  53.257979 -2.785556

### [write] Create new column for address geocoding

In [ ]:
import ibis
from utils.f_0_dirs import get_data_dirs
from f_3_spatial import convert_dms_to_decimal

old_table_name = "fame_fixed_filtered"
new_table_name = "working_fixed"

# Initialize connection
dirs = get_data_dirs()
con = ibis.duckdb.connect(str(dirs.db_path))
con.raw_sql("INSTALL spatial; LOAD spatial;")

# Reference the existing tables
fame_fixed = con.table(old_table_name)

# 1. Parse availability into an indicator and extract the best available text address
sep: ibis.StringScalar = ibis.literal(", ", type="string")
working_raw = fame_fixed.mutate(
    address_raw_lvl = build_location_source_cases(fame_fixed, address_hierachy),
    address_raw = ibis.coalesce(
        fame_fixed.primary_trading_address,
        fame_fixed.ro_address,
        # Fallback: concatenate the separate lines and postcode if above are null
        sep.join(
            ibis.array([
                fame_fixed.ro_address_line_1, 
                fame_fixed.ro_address_line_2, 
                fame_fixed.ro_full_postcode
            ]).filter(lambda x: x.notnull())
        ),
        fame_fixed.ro_full_postcode,
        fame_fixed.ro_postcode
    )
)

# 2. Extract and clean postcodes for Levels 2, 4, 5, 6, and 7
# Regex matches standard UK postcode formats. We strip whitespace and uppercase for perfect joins.
# 2. Extract and clean postcodes for Levels 2, 4, 5, 6, and 7
# Regex matches standard UK postcode formats. 
uk_postcode_regex = r"([A-Za-z]{1,2}\d[A-Za-z\d]?\s?\d[A-Za-z]{2})"

working_pc = working_raw.mutate(
    extracted_postcode = ibis.cases(
        (working_raw.address_raw_lvl.isin([1, 2]), working_raw.primary_trading_address.re_extract(uk_postcode_regex, 1)),
        (working_raw.address_raw_lvl.isin([3, 4]), working_raw.ro_address.re_extract(uk_postcode_regex, 1)),
        (working_raw.address_raw_lvl.isin([5, 6]), working_raw.ro_full_postcode),
        (working_raw.address_raw_lvl == 7, working_raw.ro_postcode),
        else_=ibis.literal(None, type="string")
    )
    .cast("string")
    .upper()
    .re_replace(r"\s+", "") # Step 1: Strip all existing spaces (e.g. "EC1Y2AL" or "EC1Y  2AL" -> "EC1Y2AL")
    .re_replace(r"(.+)(\d[A-Z]{2})$", r"\1 \2") # Step 2: Insert exactly one space before the 3-character inward code
)

# Clean the ONS directory postcodes using the same logic for the join
ons_table_name = "ref_ons_postcode" # Assume this exists with 'postcode', 'lat', 'long'
ons_lookup = con.table(ons_table_name) 

# 3. Join firm data with the ONS lookup
working_joined = working_pc.left_join(
    ons_lookup,
    working_pc.extracted_postcode == ons_lookup.pcds
)

# 4. Extract standardized spatial coordinates based on ALL 7 levels of the hierarchy
working_fixed = working_joined.mutate(
    address_case = ibis.cases(
        (working_joined.address_raw_lvl <= 2, ibis.literal('pta')),
        (working_joined.address_raw_lvl <= 7, ibis.literal('ro')),
        else_=ibis.literal(None, type="string")
    ),
    address_lvl = ibis.cases(
        (working_joined.address_raw_lvl <= 2, working_joined.address_raw_lvl),
        (working_joined.address_raw_lvl <= 7, working_joined.address_raw_lvl - 2),
        else_=ibis.literal(None, type="int64")
    ),
    lat_dec = ibis.cases(
        (working_joined.address_raw_lvl == 1, convert_dms_to_decimal(working_joined.primary_trading_address_latitude)),
        (working_joined.address_raw_lvl == 3, convert_dms_to_decimal(working_joined.ro_latitude)),
        else_=working_joined.lat # ibis.literal(None, type='float64') # # Automatically covers levels 2, 4, 5, 6, and 7
    ),
    lon_dec = ibis.cases(
        (working_joined.address_raw_lvl == 1, convert_dms_to_decimal(working_joined.primary_trading_address_longitude)),
        (working_joined.address_raw_lvl == 3, convert_dms_to_decimal(working_joined.ro_longitude)),
        else_=working_joined.long # ibis.literal(None, type='float64') # # Automatically covers levels 2, 4, 5, 6, and 7
    )
)

working_fixed_loc = working_fixed.select('registered_number', 'address_raw', 'extracted_postcode',
         'address_case', 'address_lvl', 'lat_dec', 'lon_dec')
# ).drop("extracted_postcode", "postcode", "lat", "long") # Drop join artifacts

row_count = working_fixed_loc.count().execute()
display(working_fixed_loc.sample(30 / row_count).execute())

❌ DATA_DIR path does not exist or is not a directory: /mnt/h/Other computers/My computer/fame_clean/1_FAME_raw_data/2025.07.30

,registered_number,address_raw,extracted_postcode,address_case,address_lvl,lat_dec,lon_dec
0,07308880,"Lancaster House, Drayton Road, Shirley, Solihu...",B90 4NG,pta,1,52.398861,-1.802889
1,12744628,"The Old Grange, Warren Estate, Lordship Road, ...",CM1 3WT,ro,1,51.736139,0.429139
2,04361700,"1110 Elliott Court, Coventry Business Park, Co...",CV5 6UB,ro,1,52.403194,-1.553972
3,13728881,"54 Cubbington Road, Coventry, West Midlands, C...",CV6 7BN,pta,2,52.442847,-1.483345
4,07051686,"c/o Portal House, Unit 2, Botterley Court, Nan...",CW6 9GT,pta,2,53.117982,-2.598863
5,SC130376,"Suite 9 River Court, 5 West Victoria Dock Road...",DD1 3JT,ro,2,56.459560,-2.961632
6,10130324,"Unit 9 Victory Park, Victory Road, Derby, Derb...",DE24 8ZF,ro,1,52.892750,-1.471167
7,06427917,"Satago Cottage, 360A Brighton Road, Croydon, S...",CR2 6AL,ro,1,51.350000,-0.100167
8,SC237325,"Capital Square, 58 Morrison Street, Edinburgh,...",EH3 8EP,ro,2,55.947945,-3.192256
9,SC191533,"210 Edmiston Drive, Glasgow, Lanarkshire, G51 2YU",G51 2YU,ro,1,55.853167,-4.314111
10,05379264,"Unit G Moreton Business Park, Moreton-On-Lugg,...",HR4 8DS,pta,2,52.116077,-2.728665
11,SC412275,"Forres Town Hall High Street, Forres, Morayshi...",IV36 1PB,pta,2,57.610740,-3.611997
12,05223745,"38 De Montfort Street, Leicester, Leicestershi...",LE1 7GS,ro,1,52.627389,-1.125444
13,09985534,"c/o Duff And Phelps Ltd, The Chancery, Manches...",M2 1EW,ro,2,53.480220,-2.242405
14,07981279,"483 Green Lanes, London, London, N13 4BS",N13 4BS,pta,1,51.509139,-0.132333
15,13669826,"2nd Floor 41-51 Grey Street, Newcastle Upon Ty...",NE1 6EE,pta,2,54.971472,-1.611687
16,04855747,"Cedarwood Trust Avon Avenue, North Shields, Ty...",NE29 7QT,pta,1,55.004083,-1.464944
17,02834353,"Union House, University Plain, University Of E...",NR4 7TJ,pta,1,52.622750,1.242389
18,04869022,"Hooton Street Carlton Road, Nottingham, Nottin...",NG3 2NJ,pta,1,52.957972,-1.125472
19,13647551,"2nd Floor Rowood House, Murdock Road, Bicester...",OX26 4PP,pta,2,51.902372,-1.142638
20,08432450,"4 Church Street, Stilton, Peterborough, Cambri...",PE7 3RF,pta,1,52.489556,-0.289056
21,02858337,"Ashbrook House Westbrook Street, Blewbury, Did...",OX11 9QA,ro,1,51.569056,-1.238417
22,06517935,"Speed Medical House, 16 Eaton Avenue, Chorley,...",PR7 7NA,ro,2,53.686620,-2.672618
23,07074381,"c/o Kre Corporate Recover Llp, Hedrich House 1...",RG1 1SN,ro,1,51.456000,-0.971472
24,09335968,"2nd Floor South 100 Brook Drive, Green Park, R...",RG2 6UJ,pta,2,51.425828,-0.984966
25,04737718,"Heath Clark 1st Floor, Spire Walk, Chesterfiel...",S40 2WG,ro,2,53.230920,-1.423734
26,01893924,"165-167 Railton Road, London, London, SE24 0LU",SE24 0LU,pta,1,51.456333,-0.105722
27,02693859,"Craegmoor House, Perdiswell Park, Worcester, H...",WR3 7NW,pta,1,52.211250,-2.226556
28,00580220,"Scarborough College Filey Road, Scarborough, N...",YO11 3BA,pta,2,54.264544,-0.396804
29,06729061,"Dalton Airfield, Dalton, Thirsk, North Yorkshi...",YO7 3HE,pta,2,54.173189,-1.361649
30,05101442,"4 Wilkinson Business Park, Clywedog Road South...",NaN,pta,1,53.036056,-2.940722

In [7]:
working_fixed_skinny = working_fixed    \
    .mutate(
        is_public = working_fixed.ticker_symbol.notnull()

    # fame_fixed variables which we want to keep for the regression
    ).select(
        'registered_number', 'company_name', 'is_public', 'industry_codes', 'file_codes',
        'primary_uk_sic_2007_code', 'primary_uk_sic_2007_description',

    # new location variables
        'lat_dec', 'lon_dec', 'address_lvl', 'address_case'
    )

print(f"✅ Inserting columns into new '{new_table_name}' table.")
con.create_table(new_table_name, working_fixed_skinny, overwrite=True)

# Verify the final materialized table
final_table = con.table(new_table_name)
row_count = final_table.count().execute()
col_count = len(final_table.columns)

print(f"✅ Materialized '{new_table_name}' table.")
print(f"📊 Number of rows: {row_count:,}")
print(f"📊 Number of columns: {col_count}")
print(f"\nSample of {new_table_name}:")
display(final_table.sample(30 / row_count).execute())

✅ Inserting columns into new 'working_fixed' table.
✅ Materialized 'working_fixed' table.
📊 Number of rows: 152,379
📊 Number of columns: 11

Sample of working_fixed:

,registered_number,company_name,is_public,industry_codes,file_codes,primary_uk_sic_2007_code,primary_uk_sic_2007_description,lat_dec,lon_dec,address_lvl,address_case
0,03671019,WHITES ENGINEERING LIMITED,False,30,22_37 1,30990,Manufacture of other transport equipment n.e.c.,52.761556,-0.643833,1,pta
1,12432902,RICHARDSON CARE HOLDINGS LIMITED,False,87,19_22,87900,Other residential care activities,52.261488,-0.898416,2,pta
2,11974148,PST HOLDINGS LIMITED,False,64,12_47,64209,Activities of other holding companies (not inc...,51.167942,-2.698118,2,ro
3,10746789,WEBCARE GROUP LIMITED,False,64,12_47,64209,Activities of other holding companies (not inc...,53.592111,-2.420139,1,ro
4,03887202,B W EUROPE LIMITED,False,82,10_14 2,82990,Other business support service activities n.e.c.,51.415972,-0.755611,1,ro
5,01819517,AUTOSTART (MIDLANDS) LIMITED,False,71,18_27,71129,Other engineering activities (not including en...,52.565500,-1.820889,1,ro
6,07237305,OASIS COMMUNITY HUB: WATERLOO,False,"93,88","17_15,16_50",88990,Other social work activities without accommoda...,51.497056,-0.111722,1,pta
7,02592883,BAP GROUP LIMITED,False,52,17_05,52103,Operation of warehousing and storage facilitie...,51.888185,0.894119,2,ro
8,05459368,GWP GROUP LIMITED,False,17,22_05,17219,Manufacture of paper and paperboard containers...,52.364151,-1.468077,2,ro
9,09827436,8 SLICES LIMITED,False,56,17_22,56101,Licensed restaurants,52.483750,-1.281472,1,ro
10,07010566,TRADESHIFT NETWORK LTD,False,62,18_29,62020,Computer consultancy activities,51.499982,-0.133450,2,ro
11,01228114,BRITISH KIDNEY PATIENT ASSOCIATION(THE),False,88,16_50,88990,Other social work activities without accommoda...,51.145917,-0.973750,1,pta
12,03444649,BRIGHTWATER PROJECTS LIMITED,False,41,23_28,41100,Development of building projects,50.912472,-1.400694,1,ro
13,SC435540,CULTURE AND LEISURE NL LIMITED,False,"91,90","16_29,17_06 2",90010,Performing arts,55.862889,-4.031278,1,pta
14,04494132,BRAKE BROS HOLDING III LIMITED,False,70,16_56 3,70100,Activities of head offices,51.504889,-0.018778,1,ro
15,01970580,DR. J.H. BURGOYNE & PARTNERS (INTERNATIONAL) L...,False,74,18_57,74909,"Other professional, scientific and technical a...",51.518889,-0.097917,1,pta
16,04237091,WILTON AND BAIN LIMITED,False,78,14_35,78109,Activities of employment placement agencies (o...,51.515643,-0.090132,2,pta
17,07061516,AFEX MARKETS LIMITED,False,64,12_48,64999,"Other financial service activities, except ins...",51.515444,-0.089417,1,ro
18,11380591,NEBEUS SOLUTIONS LIMITED,False,"66,64,62","13_10 2,12_48 4,18_38 2",64999,"Other financial service activities, except ins...",51.511893,-0.092350,2,pta
19,03689001,NTT DATA BUSINESS SOLUTIONS LIMITED,False,62,18_29,62020,Computer consultancy activities,51.515056,-0.107917,1,pta
20,10869370,THE CEDARS LEARNING TRUST,False,85,17_31,85200,Primary education,51.680861,-0.038000,1,pta
21,02823583,T.D.R. TRANSPORT SERVICES LIMITED,False,49,16_44,49410,Freight transport by road,52.498688,-2.169895,2,ro
22,01122942,ADM PROTEXIN LIMITED,False,10,23_18,10890,Manufacture of other food products n.e.c.,53.481442,-2.256004,2,pta
23,01196539,ALISCAFF LIMITED,False,25,22_22,25990,Manufacture of other fabricated metal products...,51.645111,-0.254028,1,ro
24,08943865,ELYSIUM HEALTHCARE (GREGORY HOUSE) LIMITED,False,87,19_22,87200,Residential care activities for learning disab...,51.658235,-0.267948,2,pta
25,07019834,PRINTCRAFT LIMITED,False,18,22_06,18129,Printing (other than printing of newspapers an...,53.710472,-1.522889,1,pta
26,04015968,FREELAND HORTICULTURE LIMITED,False,81,14_50,81300,Landscape service activities,51.409483,0.175061,2,pta
27,04265102,PROCENTIA LIMITED,False,62,18_29,62012,Business and domestic software development,51.530056,-2.547639,1,pta
28,NI007231,J.H.C.HARDWARE LIMITED,False,46,15_16,46499,Wholesale of household goods (other than music...,54.626817,-5.908846,2,ro
29,05892537,ENVAIR LIMITED,False,74,18_57,74909,"Other professional, scientific and technical a...",53.581329,-2.238981,2,ro
30,02088545,NORTHERN SKILLS GROUP BUSINESS SERVICES LIMITED,False,85,17_31,85320,Technical and vocational secondary education,54.580417,-1.227111,1,pta
31,11723826,ITV SPY LIMITED,False,59,18_17,59113,Television programme production activities,51.514249,-0.228882,2,pta
32,02882166,MUNDOCOM UK LIMITED,False,73,18_48,73110,Advertising agencies,51.510333,-0.224556,1,ro
33,02257381,LONGBRIDGE SEARCH & SELECTION LIMITED,False,78,14_35,78200,Temporary employment agency activities,53.798333,-1.545111,1,pta
34,06913368,5 HERTFORD STREET LIMITED,False,82,10_05,82990,Other business support service activities n.e.c.,51.516806,-0.109750,1,ro
35,03419833,ELECTRA-NET (UK) LIMITED,False,43,12_02,43210,Electrical installation,51.519112,-0.181704,2,ro
36,08474528,LOCKER HOLDINGS LIMITED,False,06,12_42,6200,Extraction of natural gas,53.391639,-2.575500,1,pta
37,08171068,LYMM HIGH SCHOOL,False,85,17_31,85310,General secondary education,53.378704,-2.459497,2,pta
38,03295664,MARAZION HOLDINGS LIMITED,False,70,16_55,70100,Activities of head offices,50.125167,-5.476917,1,pta
39,07697494,VERDANT LEISURE 2 LIMITED,False,55,19_14,55201,Holiday centres and villages,54.069139,-2.779278,1,pta